spring:
 jpa:
  hibernate:
   ddl-auto: create-drop
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: false

 h2:
  console:
   enabled: true
 datasource:
  url: jdbc:h2:file:./testClever/db
  driver-class-name: org.h2.Driver
  username: sa
  password: